# Configuração do SonarQube para o projeto fe-video-slice (React)
sonar.projectKey=11soat-hackton-videoslice_fe-video-slice
sonar.organization=11soat-hackton-videoslice
sonar.projectName=fe-video-slice
sonar.token=${SONAR_TOKEN}
sonar.projectVersion=1.0
sonar.branch.name=master
sonar.qualitygate.wait=true

# Configurações de SCM
sonar.scm.provider=git
sonar.scm.forceReloadAll=false

# Diretórios de código fonte (React/JavaScript)
sonar.sources=src
sonar.tests=src

# Diretório de exclusões
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.js,**/*.spec.js,**/.coverage/**,**/dist/**,**/__pycache__/**

# Linguagem (JavaScript)
sonar.language=js

# Node.js configuration
sonar.nodejs.executable=auto
sonar.javascript.node.maxspace=4096

# Cobertura de testes (Jest)
sonar.junit.reportPaths=vdsc-react-app/junit.xml
sonar.javascript.lcov.reportPaths=vdsc-react-app/coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/node_modules/**,**/build/**,**/aws-config.js,**/setupTests.js
sonar.test.inclusions=**/*.test.js,**/*.spec.js


# Encoding
sonar.sourceEncoding=UTF-8

# Métricas de qualidade
sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
sonar.cpd.exclusions=**/*.test.js,**/*.spec.js

# Configurações específicas para React/Frontend
sonar.javascript.node.maxspace=4
sonar.exclusions.homepage=true

# Diretório de cobertura de código
sonar.coverage.reportPaths=vdsc-react-app/coverage

